name: "Healthy, Lean and Fit"
slogan: "Powered by Isagenix Nutrition"
mainUrl : "www.HealthyLeanAndFit.com"
description: "A group of fun individuals that share the Isagenix nutrition. Isagenix is the best nutrition in the market. Isagenix is the world leader in healthy weight loss."

mainNav:
    - title  : "Home"
      urlSlug: "/"
    - title  : "Isagenix"
      urlSlug: "#isagenix"
      subNav :
        - title  : "Why Isagenix"
          urlSlug: "/why-isagenix/"
        - title  : "Isagenix Systems"
          urlSlug: "/compare-isagenix-systems/"
        - title  : "Become an Isagenix Consultant"
          urlSlug: "/become-isagenix-consultant/"
        - title  : "Isagenix Blog"
          urlSlug: "/isagenix-blog/"
    - title  : "About Us"
      urlSlug: "/about-us/"
    - title  : "Success Stories"
      urlSlug: "/success-stories/"
    - title  : "Contact"
      urlSlug: "/contact/"

addressLine1: "Orlando, FL, USA"
addressLine2: "Tampa, FL, USA"
addressLine3: "Gainesville, FL, USA"
footerAddress: "Orlando, FL, USA<br />Tampa, FL, USA<br />Gainesville, FL, USA"
footerTelephone: "407.952.0146"
footerEmail: "&#106;&#111;&#122;&#101;&#064;&#104;&#101;&#097;&#108;&#116;&#104;&#121;&#108;&#101;&#097;&#110;&#097;&#110;&#100;&#102;&#105;&#116;&#046;&#099;&#111;&#109;"

nineDayCleanse:
    title      : "Isagenix 9 day deep cleanse"
    url        : "/isagenix-9-day-deep-cleanse/"
    keywords   : "Isagenix 9 day deep cleanse, Isagenix Cleansing, Isagenix Weight-Loss, Cellular Cleansing"
    widgetTitle: "Isagenix<br /> 9 day deep cleanse"
thirtyDayCleanse:
    title      : "Isagenix 30 day cleansing and fat burning system"
    url        : "/isagenix-30-day-cleansing-and-fat-burning-system/"
    keywords   : "Isagenix 30 day cleansing and fat burning system, 30 day cleanse, Isagenix Cleansing, Isagenix Long term Weight-Loss, Cellular Cleansing"
    widgetTitle: "Isagenix<br /> 30 day fat burning"
thirtyDayPerformance:
    title      : "Isagenix 30 day performance system"
    url        : "/isagenix-30-day-performance-pak-system/"
    keywords   : "Isagenix 30 day performance pak system, 30 day performance, IsaLean® Pro Shake, Superior muscle recovery, Superior muscle growth"
    widgetTitle: "Isagenix<br /> 30 day performance"
presidentPak:
    title      : "Isagenix Presidents Pak"
    url        : "/isagenix-presidents-pak/"
    keywords   : "Isagenix President's Pak, Isagenix Weight Loss President’s Pak, Isagenix Performance President’s Pak, Isagenix Healthy Aging President’s Pak, Isagenix Rejuvity President’s Pak"
    widgetTitle: "Isagenix<br /> Presidents Pak"