name: "Healthy, Lean and Fit"
mainUrl : "www.HealthyLeanAndFit.com"
mainNav:
    - title  : "Home"
      urlSlug: "/"
    - title  : "Isagenix"
      urlSlug: "#isagenix"
      subNav :
        - title  : "Why Isagenix"
          urlSlug: "/why-isagenix/"
        - title  : "Isagenix Systems"
          urlSlug: "/compare-isagenix-systems/"
        - title  : "Other Isagenix Products"
          urlSlug: "/isagenix-products/"
        - title  : "Isagenix Blog"
          urlSlug: "/isagenix-blog/"
    - title  : "About Us"
      urlSlug: "/about-us/"
    - title  : "Success Stories"
      urlSlug: "/success-stories/"
    - title  : "Contact"
      urlSlug: "/contact/"
addressLine1: "Orlando, FL, USA"
addressLine2: "Tampa, FL, USA"
addressLine3: "Gainesville, FL, USA"
footerAddress: "Orlando, FL, USA<br />Tampa, FL, USA<br />Gainesville, FL, USA"
footerTelephone: "407.952.0146"
footerEmail: "&#106;&#111;&#122;&#101;&#064;&#104;&#101;&#097;&#108;&#116;&#104;&#121;&#108;&#101;&#097;&#110;&#097;&#110;&#100;&#102;&#105;&#116;&#046;&#099;&#111;&#109;"